/* ******************************************************************
 * Copyright 2014-2024 ADVENTURE Project
 * All Rights Reserved
 * ****************************************************************** */
/**
 * @file RandomNumberGenerator.hpp
 */
#ifndef __RANDOM_NUMBER_GENERATOR_HPP__
#define __RANDOM_NUMBER_GENERATOR_HPP__

#include "Config.hpp"
#include "RandomSeedManager.hpp"
#include <xsadd.h>
#include <algorithm>
#include <cassert>
#include <climits>
#include <cmath>
#include <random>
#include <vector>

/**
 * @defgroup  Random
 * @~japanese 乱数生成
 * @~english  Random number generation
 */

//######################################################################
/**
 * @~japanese 乱数生成エンジン
 *
 * XSaddによって生成された乱数を分布生成器に渡すためのクラス．
 * 詳細は lib/XSadd を参照．
 * 
 * @note
 * 斎藤睦夫・松本眞による疑似乱数生成器
 * http://www.math.sci.hiroshima-u.ac.jp/m-mat/MT/XSADD/index-jp.html
 *
 * @~english  Random number generating engine
 *
 * A class for passing random number generated by XSadd to distribution
 * generators. See lib/XSadd for details.
 *
 * @note
 * Pseudo random number generator by M. Saito and M. Matsumoto
 * http://www.math.sci.hiroshima-u.ac.jp/m-mat/MT/XSADD/index.html
 *
 * @~ @ingroup Random
 */
class xsadd_random_engine
{
public:
    xsadd_random_engine()
    {
        xsadd_init(&_gen, 0);
    }

    /**
     * @~japanese 戻り値の型
     * @~english  Return value type
     */
    using result_type = unsigned int;

    /**
     * @~japanese 乱数の種を設定する
     * @~english  Set random seed
     */
    void seed(unsigned int seed)
    {
        xsadd_init(&_gen, seed);
    }

    /**
     * @~japanese xsadd_uint32()が返す最小値
     * @~english  Minimum value returned by xsadd_uint32()
     */
    static constexpr result_type min()
    {
        return 0;
    }

    /**
     * @~japanese xsadd_uint32()が返す最大値
     * @~english  Maximum value returned by xsadd_uint32()
     */
    static constexpr result_type max()
    {
        return UINT32_MAX;
    }

    /**
     * @~japanese XSaddはmin()からmax()までの値を返す
     * @~english  XSadd returns values from min() to max()
     */
    result_type operator()()
    {
        return xsadd_uint32(&_gen);
    }

    /**
     * @~japanese
     * @p z 回だけ擬似乱数を生成し内部状態を進める
     *
     * @~english
     * Generate random number @p z times and proceed internal state 
     */
    void discard(unsigned long long z)
    {
        for (unsigned long long i = 0; i < z; i++)
        {
            xsadd_uint32(&_gen);
        }
    }

private:
    /**
     * @~japanese 乱数生成エンジン本体
     * @~english  Substance of random number generating engine
     */
    xsadd_t _gen;
};

//######################################################################
/**
 * @~japanese 
 * 乱数生成器
 *
 * 指定された分布の乱数を生成する
 *
 * @note
 * 環境によって分布生成器の実装が異なり結果が変わる恐れがあるため，
 * c++11に標準で含まれる分布生成器は使用しない
 *
 * @todo
 * リスタートのための機能．seed(_seed)とdiscard(_numCalled)を利用．
 *
 * @~english
 * Random number generator
 *
 * Generate random number with specified distribution
 *
 * @note
 * Distribution generators included in c++11 standard are not used,
 * because their implementation may vary depending on the environment
 * and the simulation result may change.
 *
 * @~ @ingroup Random
 */
class RandomNumberGenerator
{
    /**
     * @~japanese 使用される乱数生成エンジン
     * @~english  Random number generating engine being used
     */
    using RANDOM_ENGINE = xsadd_random_engine;
    //  std::default_random_engine;
    //  std::minstd_rand;
    //  std::mt19937;
    //  std::ranlux24;
    //  std::ranlux48;
    //  std::knuth_b;

public:
    RandomNumberGenerator()
    {
        _engine    = nullptr;
        _seed      = 0;
        _numCalled = 0;
    }

    ~RandomNumberGenerator()
    {
        if (_engine)
        {
            delete _engine;
        }
    };

    /**
     * @~japanese 
     * 乱数生成エンジンを付与する
     *
     * 乱数生成エンジンは内部でRandomEngineManagerから取得する
     *
     * @~english
     * Assign random number generating engine
     *
     * Get random number generating engine from RandomEngineManager
     * internally.
     */
    void reset();

    /**
     * @~japanese 
     * 乱数生成エンジンを付与する (advmates-sim用)
     *
     * 乱数生成エンジンは内部でRandomEngineManagerから取得する
     *
     * @note
     * advmates-calcとadvmates-simで同一の結果を出力するために，
     * advmates-simでのみ使用される乱数生成エンジンは別に管理する
     *
     * @~english
     * Assign random number generating engine (for advmates-sim)
     *
     * Get random number generating engine from RandomEngineManager
     * internally.
     *
     * @note
     * In order to output the same result with advmates-calc and
     * advmates-sim, the random number generation engine used only
     * in advmates-sim should be managed separately.
     */
    void resetForSim();

    //==================================================================
    /**
     * @~japanese
     * [ 0, @p max ) の一様分布に従うint型変数を取得する
     *
     * @~english 
     * Get int-type value uniformly distributed on [ 0, @p max )
     */
    int uniform(int max)
    {
        _numCalled++;
        return (*_engine)() % max;
    }

    //==================================================================
    /**
     * @~japanese
     * [ @p min, @p max ) の一様分布に従うint型変数を取得する
     *
     * @~english 
     * Get int-type value uniformly distributed on [ @p min , @p max )
     */
    int uniform(int min, int max)
    {
        return min + uniform(max - min);
    }

    //==================================================================
    /**
     * @~japanese
     * [ 0, 1 ] の一様分布に従うdouble型変数を取得する
     *
     * @~english 
     * Get double-type value uniformly distributed on [ 0, 1 ]
     */
    double uniform()
    {
        _numCalled++;
        return static_cast<double>((*_engine)() - _engine->min())
            / (_engine->max() - _engine->min());
    }

    //==================================================================
    /**
     * @~japanese
     * 平均 @p mu , 標準偏差 @p sigma の正規分布に従うdouble型変数を
     * 取得する
     *
     * @~english
     * Get normally distributed double-type value with mean @p mu and
     * standard deviation @p sigma.
     */
    double normal(double mu, double sigma)
    {
        // Box–Muller's method
        double x = uniform();
        double y = uniform();
        double z = std::sqrt(-2 * std::log(x)) * std::cos(2 * M_PI * y);
        return mu + sigma * z;
    }

    //==================================================================
    /**
     * @~japanese
     * 平均 @p lambda のポアソン分布に従うint型変数を取得する
     *
     * @~english
     * Get Poisson-distributed int-type value with mean @p lambda
     */
    int poisson(double lambda)
    {
        int    k;
        double p = std::exp(lambda) * uniform();
        for (k = 0; p > 1.0; k++)
        {
            p *= uniform();
        }
        return k;
    }

    //==================================================================
    /**
     * @~japanese
     * 平均 1/@p lambda の指数分布に従うdouble型変数を取得する
     *
     * @~english
     * Get exponentially distributed double-type value with mean
     * 1/@p lambda
    */
    double exponential(double lambda)
    {
        return -std::log(uniform()) / lambda;
    }

    //==================================================================
    /**
     * @~japanese
     * 確率が @p p で真となるBernoulli試行による真偽値を取得する
     *
     * @~english
     * Get boolean value from Bernoulli trial that is true with
     * probability @p p
     */
    bool bernoulli(double p)
    {
        return (uniform() <= p);
    }

    //==================================================================
    /**
     * @~japanese
     * [ 0, @p size )の間の整数がシャッフルされた数列を生成する
     *
     * @~english
     * Generate sequence of shuffled integers between [ 0, @p size )
     */
    std::vector<int> getShuffled(int size)
    {
        std::vector<int> result(size);
        std::iota(result.begin(), result.end(), 0);
        if (size > 1)
        {
            // Fisher–Yates shuffle
            for (unsigned int i = size; i > 1; i--)
            {
                std::swap(result[i - 1], result[uniform(i)]);
            }
        }
        return result;
    }

    //==================================================================
    /**
     * @~japanese @name アクセッサ
     * @~english  @name Accessor
     */
    ///@{
    RANDOM_ENGINE& engine()
    {
        return *_engine;
    }
    void setEngine(RANDOM_ENGINE* engine)
    {
        _engine = engine;
    }
    unsigned int seed() const
    {
        return _seed;
    }
    unsigned long long numCalled() const
    {
        return _numCalled;
    }
    ///@}

private:
    /**
     * @~japanese 乱数生成エンジン
     * @~english  Random number generating engine
     */
    RANDOM_ENGINE* _engine;

    /**
     * @~japanese
     * 乱数生成エンジンに与えたシード
     *
     * @note
     * リスタート機能のためにエンジン外部で保存する
     *
     * @~english
     * Seed given to random number generating engine
     *
     * @note
     * Save outside the engine for restart
     */
    unsigned int _seed;

    /**
     * @~japanese
     * 乱数生成エンジンの呼び出し回数
     *
     * @~english
     * Number of calls to random number generating engine
     */
    unsigned long long _numCalled;
};

#endif //__RANDOM_NUMBER_GENERATOR_HPP__
