/* ******************************************************************
 * Copyright 2014-2024 ADVENTURE Project
 * All Rights Reserved
 * ****************************************************************** */
/**
 * @file VehicleScene.hpp
 */
#ifndef __VEHICLE_SCENE_HPP__
#define __VEHICLE_SCENE_HPP__
#include <iostream>
#include <vector>

class Lane;
class Vehicle;
class VirtualLeader;

//######################################################################
/**
 * @~japanese
 * 自動車エージェントの意思決定に必要な局所環境を集約する構造体
 *
 * VehiclePerceiver ，VehicleLaneChangePerceiver によって生成され，
 * おもに VehicleDeterminer ， VehicleLaneChangeDeterminer が利用．
 *
 * @~english
 * Struct aggregating local environment necessary for decision-making
 * of the car agent
 *
 * Generated by VehiclePerceiver and VehicleLaneChangePerceiver , and
 * mainly used by VehicleDeterminer and VehicleLaneChangeDeterminer.
 *
 * @~
 * @ingroup Vehicle
 */
struct VehicleScene
{
public:
    VehicleScene();
    ~VehicleScene()
    {
        clear();
    }

    /**
     * @~japanese 前ステップの認知結果をクリアする
     * @~english  Clear the recognized result of the previous step
     */
    void clear();

    /**
     * @~japanese 仮想先行車 @p leader を追加する
     * @~english  Add a virtual leader @p leader
     */
    void addLeader(const VirtualLeader* leader)
    {
        _leaders.push_back(leader);
    }

    void setAdjLeader(const Vehicle* leader, double diff)
    {
        _adjLeader     = leader;
        _adjLeaderDiff = diff;
    }

    void setAdjFollower(const Vehicle* follower, double diff)
    {
        _adjFollower     = follower;
        _adjFollowerDiff = diff;
    }

    void setInterruptingLeader(const Vehicle* leader, double diff)
    {
        _interruptingLeader     = leader;
        _interruptingLeaderDiff = diff;
    }

    void setInterruptingFollower(const Vehicle* follower, double diff)
    {
        _interruptingFollower     = follower;
        _interruptingFollowerDiff = diff;
    }

    /**
     * @~japanese 認知結果を @p out に出力する
     * @~english  Output the recognized result to @p out
     */
    void print(std::ostream& out) const;

private:
    /**
     * @~japanese 所有者
     * @~english  Owner
     */
    const Vehicle* _vehicle;

    /**
     * @~japanese 自動車エージェントが認知した制限速度 [m/ms]
     * @~english  Speed ​​limit recognized by car agent [m/ms]
     */
    double _vMax;

    /**
     * @~japanese 仮想先行車
     * @~english  Virtual leaders
     */
    std::vector<const VirtualLeader*> _leaders;

    /**
     * @~japanese 希望ヘッドウェイ [ms]
     * @~english  Desired headway [ms]
     */
    double _desiredHeadway;

    /**
     * @~japanese 変更希望車線
     *
     * @note
     * 実現可能か否かに関わらず，車線変更先として希望する車線．
     * 他者から認知される場合は VehicleDecision::laneTo() を用いる．
     *
     * @~english  Desired lane to change to
     *
     * @note
     * Desired lane to change to, whether feasible or not.
     * Use VehicleDecision::laneTo() when recognized by others.
     */
    const Lane* _desiredLaneTo;

    /**
     * @~japanese 変更希望車線における位置
     *
     * @note
     * 現在の位置を変更希望車線上に投影した位置．
     * 他者から認知される場合は VehicleBehavior::distanceTo() を用いる．
     *
     * @~english  Position in desired lane to change to
     *
     * @note
     * Projected position of the current position on the desired lane.
     * Use VehicleBehavior::distanceTo() when recognized by others.
     */
    double _desiredDistanceTo;

    /**
     * @~japanese 変更希望車線における先行車
     * @~english  Leading car in the desired lane to change to
     */
    const Vehicle* _adjLeader;

    /**
     * @~japanese
     * 変更希望車線における先行車までの距離
     *
     * @~english
     * Distance to the leading car in the desired lane to change to
     */
    double _adjLeaderDiff;

    /**
     * @~japanese 変更希望車線における後続車
     * @~english  Following car in the desired lane to change to
     */
    const Vehicle* _adjFollower;

    /**
     * @~japanese
     * 変更希望車線における後続車までの距離
     *
     * @~english
     * Distance to the following car in the desired lane to change to
     */
    double _adjFollowerDiff;

    /**
     * @~japanese 自車の前方に割り込む車両
     * @~english  Car interrupting into the front of the subject car
     */
    const Vehicle* _interruptingLeader;

    /**
     * @~japanese 割り込む車両までの距離
     * @~english  Distance to interrupting car
     */
    double _interruptingLeaderDiff;

    /**
     * @~japanese 自車に割り込まれる車両
     * @~english  Car being interrupted by the subject car
     */
    const Vehicle* _interruptingFollower;

    /**
     * @~japanese 割り込まれる車両までの距離
     * @~english  Distance to interrupted car
     */
    double _interruptingFollowerDiff;

    //==================================================================
    /**
     * @~japanese @name アクセッサ
     * @~english  @name Accessor
     */
    ///@{
public:
    void setVehicle(const Vehicle* vehicle)
    {
        _vehicle = vehicle;
    }

    double vMax() const
    {
        return _vMax;
    }

    void setVMax(double vMax)
    {
        _vMax = vMax;
    }

    const std::vector<const VirtualLeader*>& leaders() const
    {
        return _leaders;
    }

    double desiredHeadway() const
    {
        return _desiredHeadway;
    }

    void setDesiredHeadway(double desiredHeadway)
    {
        _desiredHeadway = desiredHeadway;
    }

    const Lane* desiredLaneTo() const
    {
        return _desiredLaneTo;
    }

    void setDesiredLaneTo(const Lane* lane)
    {
        _desiredLaneTo = lane;
    }

    double desiredDistanceTo() const
    {
        return _desiredDistanceTo;
    }

    void setDesiredDistanceTo(double distance)
    {
        _desiredDistanceTo = distance;
    }

    const Vehicle* adjLeader() const
    {
        return _adjLeader;
    }

    void setAdjLeader(const Vehicle* leader)
    {
        _adjLeader = leader;
    }

    double adjLeaderDiff() const
    {
        return _adjLeaderDiff;
    }

    void setAdjLeaderDiff(double diff)
    {
        _adjLeaderDiff = diff;
    }

    const Vehicle* adjFollower() const
    {
        return _adjFollower;
    }

    void setAdjFollower(const Vehicle* follower)
    {
        _adjFollower = follower;
    }

    double adjFollowerDiff() const
    {
        return _adjFollowerDiff;
    }

    void setAdjFollowerDiff(double diff)
    {
        _adjFollowerDiff = diff;
    }

    const Vehicle* interruptingLeader() const
    {
        return _interruptingLeader;
    }

    void setInterruptingLeader(const Vehicle* leader)
    {
        _interruptingLeader = leader;
    }

    double interruptingLeaderDiff() const
    {
        return _interruptingLeaderDiff;
    }

    void setInterruptingLeaderDiff(double diff)
    {
        _interruptingLeaderDiff = diff;
    }

    const Vehicle* interruptingFollower() const
    {
        return _interruptingFollower;
    }

    void setInterruptingFollower(const Vehicle* follower)
    {
        _interruptingFollower = follower;
    }

    double interruptingFollowerDiff() const
    {
        return _interruptingFollowerDiff;
    }

    void setInterruptingFollowerDiff(double diff)
    {
        _interruptingFollowerDiff = diff;
    }

    ///@}
};

#endif //__VEHICLE_SCENE_HPP__
