/* ******************************************************************
 * Copyright 2014-2024 ADVENTURE Project
 * All Rights Reserved
 * ****************************************************************** */
/**
 * @file VehicleDecision.hpp
 */
#ifndef __VEHICLE_DECISION_HPP__
#define __VEHICLE_DECISION_HPP__
#include "Config.hpp"
#include <deque>
#include <iostream>

class Lane;
class Vehicle;

//######################################################################
/**
 * @~japanese
 * 自動車エージェントの行動生成に必要な意思決定結果を集約する構造体
 *
 * VehicleDeterminer ， VehicleLaneChangeDeterminer によって生成され，
 * おもに VehicleActor ， VehicleLaneChangeActor が利用．
 *
 * @~english
 * Struct aggregating decision-making results necessary for behavior
 * generation of the car agent
 *
 * Generated by VehicleDeterminer and VehicleLaneChangeDeterminer , and
 * mainly used by VehicleActor and VehicleLaneChangeActor.
 *
 * @~
 * @ingroup Vehicle
 */
struct VehicleDecision
{
public:
    VehicleDecision();
    ~VehicleDecision() {};

    /**
     * @~japanese 車線変更のフラグをリセットする
     * @~english  Reset lane-change flags
     */
    void resetLaneChangeFlags()
    {
        _isLaneChangeRequired   = false;
        _isLaneChangeExecutable = false;
        _isLaneChangeActive     = false;
    }

    /**
     * @~japanese 意思決定結果を表示する
     * @~english  Display the decision result
     */
    void print(std::ostream& out) const;

    /**
     * @~japanese 車線変更のフラグを出力する
     * @~english  Display the lane-change flags
     */
    void printLaneChangeFlags(std::ostream& ost) const;

private:
    /**
     * @~japanese 持ち主
     * @~english  Owner
     */
    const Vehicle* _vehicle;

    /**
     * @~japanese 算出された加速度 [m/(ms^2)]
     * @~english  Calculated acceleration [m/(ms^2)]
     */
    double _decidedAccel;

    /**
     * @~japanese 休止状態になるべきか
     *
     * @note
     * determine中で _sleepDuration を変更すると他の車両のdetermineに
     * 影響するため，休止にする判断のみおこない， _sleepDuration の
     * 変更は VehicleActor::act に先延ばしする
     *
     * @~english  Whether to inactivate
     *
     * @note
     * Because changing _sleepDuration during determine will affect
     * other cars determine, only judge inactivation and postpone the
     * change of _sleepDuration to VehicleActor::act .
     */
    bool _shouldSleep;

    /**
     * @~japanese 車線変更の必要があるかどうか
     * @~english  Whether lane-change required
     */
    bool _isLaneChangeRequired;

    /**
     * @~japanese 車線変更可能かどうか
     * @~english  Whether lane-change executable
     */
    bool _isLaneChangeExecutable;

    /**
     * @~japanese 車線変更実行中かどうか
     * @~english  Whether lane-change is in process
     */
    bool _isLaneChangeActive;

    //==================================================================
    /**
     * @~japanese @name アクセッサ
     * @~english  @name Accessor
     */
    ///@{
public:
    void setVehicle(const Vehicle* vehicle)
    {
        _vehicle = vehicle;
    }

    double decidedAccel() const
    {
        return _decidedAccel;
    }

    void setDecidedAccel(double accel)
    {
        _decidedAccel = accel;
    }

    bool shouldSleep() const
    {
        return _shouldSleep;
    }

    void setShouldSleep(bool shouldSleep)
    {
        _shouldSleep = shouldSleep;
    }

    bool isLaneChangeRequired() const
    {
        return _isLaneChangeRequired;
    }

    void setIsLaneChangeRequired(bool isRequired)
    {
        _isLaneChangeRequired = isRequired;
    }

    bool isLaneChangeExecutable() const
    {
        return _isLaneChangeExecutable;
    }

    void setIsLaneChangeExecutable(bool isExecutable)
    {
        _isLaneChangeExecutable = isExecutable;
    }

    bool isLaneChangeActive() const
    {
        return _isLaneChangeActive;
    }

    void setIsLaneChangeActive(bool isActive)
    {
        _isLaneChangeActive = isActive;
    }

    ///@}
};

#endif //__VEHICLE_DECISION_HPP__
